server:
  port: 7001

eureka:
  instance:
    #hostname: localhost #eureka服务端的实例名字(单机模式)
    hostname: eureka7001.com #eureka服务端的实例名字(集群模式),eureka7001.com是在本机电脑host文件做了域名映射
  client:
    #表识不向注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机模式
      defaultZone: http://eureka7002.com:7002/eureka/  #端口号与地址相互注册,互相守望(集群模式)
  server:
    enable-self-preservation: false   #这里表示的是关闭自我保护模式,默认是true开启的
    eviction-interval-timer-in-ms: 2000  #表示的2000毫秒后没有心跳直接把该服务剔除